config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :photos #自動產生7個controller#actions的路徑資源(產生7組網址)
  root "photos#index" #將網站根目錄設定為index.html.erb這個頁面

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader #加入上傳器
  validates_presence_of :title, :date, :description, :file_location #資料驗證,確保必填
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, :only => [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save #如果能成功執行@photo.save，表示有通過驗證，可放心導入index頁面
      redirect_to photos_url
    else
      render :action => :new #反之驗證失敗，留在原頁面請使用者把資料填完
    end
  end

  def update
    if @photo.update_attributes(photo_params)
      redirect_to photo_path(@photo)
    else
      render :action => :edit
    end
  end

  def destroy
    @photo.destroy

    redirect_to photos_url
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<div class="form-page">

<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.each do |error, message| %>
      <li><%= "#{error.capitalize} #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
  <%= form_for @photo do |f| %>

    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :date, "Date" %>
      <%= f.date_select :date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :file_location, "File Location" %>
      <%= f.file_field :file_location %>
    </div>

    <%= f.submit %>
  <% end %>

  <%= link_to 'Back to Index', photos_url %>
</div>

</div>

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<div class="index-page">

  <h2>Revi's Album</h2>

  <div class="photo-list">
    <table class="table table-striped table-condensed">
      <% @photos.each do |photo| %>
        <tr>
          <td><%= photo.title %></td>
          <td><%= link_to 'Show', photo_path(photo) %></td>
          <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
          <td><%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <%= link_to 'New Photo', new_photo_path %>

</div>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<div class="show-page">

  <div class="table-responsive">
    <table>
      <tr><td><h2><%= @photo.title %></h2></td></tr>
      <tr><td><p><%= @photo.date %></p></td></tr>
      <tr><td><%= image_tag @photo.file_location.url, size: "600x400", class: "img-thumbnail" %></td></tr>
    <tr><td><p><%= simple_format(@photo.description) %></p></td></tr>
    </table>
  </div>

  <%= link_to 'Back to Index', photos_path %>

</div>